import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const rootDirectory = path.resolve(scriptDirectory, "..");
const sourcePath = path.join(
  rootDirectory,
  "data/sources/awesome-dsh-plugin.json",
);
const outputPath = path.join(rootDirectory, "content/plugins.generated.ts");

const categoryDefinitions = [
  {
    rawId: "ui",
    id: "ui-enhancements",
    label: "UI enhancements",
    description: "Interface and presentation enhancements for DSH.",
  },
  {
    rawId: "session",
    id: "sessions-and-messages",
    label: "Sessions and messages",
    description: "Conversation, memory, and session-management tools.",
  },
  {
    rawId: "tools",
    id: "tools-and-capabilities",
    label: "Tools and capabilities",
    description: "Specialized tools and capabilities for DSH agents.",
  },
  {
    rawId: "workflow",
    id: "workflow-and-automation",
    label: "Workflow and automation",
    description: "Automation and repeatable workflows for DSH.",
  },
  {
    rawId: "notify",
    id: "notifications-and-integrations",
    label: "Notifications and integrations",
    description: "Notification channels and external-service integrations.",
  },
  {
    rawId: "dev",
    id: "development-and-runtime",
    label: "Development and runtime",
    description: "Development tooling and runtime extensions.",
  },
  {
    rawId: "fun",
    id: "just-for-fun",
    label: "Just for fun",
    description: "Creative and experimental DSH plugins.",
  },
];

const categoryByRawId = new Map(
  categoryDefinitions.map((category) => [category.rawId, category]),
);

const featuredRepositories = new Set([
  "Nagi-ovo/dsh-visualize",
  "omdsh-dev/dsh-mnemon",
  "Anionex/dsh-vision-toolkit",
  "Jesse-njx/dsh-chatnode-wechat",
  "omdsh-dev/dsh-at-file",
  "huiliyi37/dsh-tianshu-tui",
]);

const communityDiscoveredDetail =
  "Community discovered. Structural bundle checks have not been done.";

function fail(message) {
  throw new Error(`Cannot generate plugin content: ${message}`);
}

function cleanDescription(description) {
  const cleaned = description
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[`*]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) {
    fail("a plugin is missing an English description");
  }

  return cleaned.length <= 220
    ? cleaned
    : `${cleaned.slice(0, 217).replace(/\s+\S*$/, "").trimEnd()}...`;
}

function pluginIdFor(repository, usedIds) {
  const baseId = repository
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (!baseId) {
    fail(`could not create an id for ${repository}`);
  }

  let id = baseId;
  let suffix = 2;
  while (usedIds.has(id)) {
    id = `${baseId}-${suffix}`;
    suffix += 1;
  }
  usedIds.add(id);
  return id;
}

function quote(value) {
  return JSON.stringify(value);
}

function renderPlugin(plugin) {
  return [
    "  {",
    `    id: ${quote(plugin.id)},`,
    `    name: ${quote(plugin.name)},`,
    `    repoUrl: ${quote(plugin.repoUrl)},`,
    `    repository: ${quote(plugin.repository)},`,
    `    description: ${quote(plugin.description)},`,
    `    category: ${quote(plugin.category)},`,
    `    installCommand: ${quote(plugin.installCommand)},`,
    "    verification: {",
    '      state: "community-discovered",',
    "      detail: communityDiscoveredDetail,",
    "    },",
    "    source: {",
    `      name: ${quote(plugin.source.name)},`,
    `      url: ${quote(plugin.source.url)},`,
    "    },",
    `    featured: ${plugin.featured},`,
    `    latest: ${plugin.latest},`,
    "  },",
  ].join("\n");
}

function renderModule(plugins) {
  const renderedCategories = categoryDefinitions
    .map((category) => [
      "  {",
      `    id: ${quote(category.id)},`,
      `    label: ${quote(category.label)},`,
      `    description: ${quote(category.description)},`,
      "  },",
    ].join("\n"))
    .join("\n");

  return `// This file is generated by scripts/generate-content.mjs. Do not edit manually.\n\nexport const categories = [\n${renderedCategories}\n] as const;\n\nexport type PluginCategory = (typeof categories)[number]["id"];\nexport type PluginCategoryDefinition = (typeof categories)[number];\n\nexport const categoryById = Object.fromEntries(\n  categories.map((category) => [category.id, category]),\n) as Record<PluginCategory, PluginCategoryDefinition>;\n\nexport const verificationStates = ["community-discovered"] as const;\n\nexport type VerificationState = (typeof verificationStates)[number];\n\nexport type PluginVerification = {\n  state: VerificationState;\n  detail: string;\n};\n\nexport type PluginSource = {\n  name: string;\n  url: string;\n};\n\nexport type Plugin = {\n  id: string;\n  name: string;\n  repoUrl: string;\n  repository: string;\n  description: string;\n  category: PluginCategory;\n  installCommand: string;\n  verification: PluginVerification;\n  source: PluginSource;\n  featured: boolean;\n  latest: boolean;\n};\n\nconst communityDiscoveredDetail = ${quote(communityDiscoveredDetail)};\n\nexport const plugins = [\n${plugins.map(renderPlugin).join("\n")}\n] as const satisfies readonly Plugin[];\n`;
}

const snapshot = JSON.parse(await readFile(sourcePath, "utf8"));
if (!Array.isArray(snapshot.plugins)) {
  fail("source snapshot does not have a plugins array");
}

if (snapshot.plugins.length !== 138) {
  fail(`expected 138 public records, found ${snapshot.plugins.length}`);
}

const seenRepositories = new Set();
const usedIds = new Set();
const normalizedPlugins = snapshot.plugins
  .map((record) => {
    if (
      typeof record.name !== "string" ||
      typeof record.owner !== "string" ||
      typeof record.url !== "string" ||
      typeof record.install !== "string" ||
      typeof record.category !== "string" ||
      typeof record.description?.en !== "string"
    ) {
      fail("a source record is missing a required field");
    }

    const repository = `${record.owner}/${record.name}`;
    const expectedUrl = `https://github.com/${repository}`;
    const expectedInstall = `dsh plugin --profile web add github:${repository}`;
    const category = categoryByRawId.get(record.category);

    if (record.url !== expectedUrl) {
      fail(`${repository} does not use an exact GitHub URL`);
    }
    if (record.install !== expectedInstall) {
      fail(`${repository} does not use the expected install command`);
    }
    if (!category) {
      fail(`${repository} has an unknown category: ${record.category}`);
    }
    if (seenRepositories.has(repository)) {
      fail(`duplicate repository: ${repository}`);
    }
    seenRepositories.add(repository);

    return {
      name: record.name,
      repoUrl: record.url,
      repository,
      description: cleanDescription(record.description.en),
      category: category.id,
      installCommand: record.install,
      source: {
        name: snapshot.name,
        url: snapshot.source,
      },
      featured: featuredRepositories.has(repository),
      latest: record.added === snapshot.updated,
    };
  })
  .sort((left, right) => {
    if (left.repository < right.repository) return -1;
    if (left.repository > right.repository) return 1;
    return 0;
  })
  .map((plugin) => ({
    ...plugin,
    id: pluginIdFor(plugin.repository, usedIds),
  }));

if (normalizedPlugins.length !== snapshot.plugins.length) {
  fail("normalization did not produce one entry per source record");
}

for (const repository of featuredRepositories) {
  if (!seenRepositories.has(repository)) {
    fail(`featured repository is not present in the source snapshot: ${repository}`);
  }
}

if (normalizedPlugins.filter((plugin) => plugin.featured).length !== 6) {
  fail("exactly six repositories must be featured");
}

await writeFile(outputPath, renderModule(normalizedPlugins), "utf8");
console.log(`Generated ${normalizedPlugins.length} plugins in ${path.relative(rootDirectory, outputPath)}.`);
